name: Sync Data and Publish

on:
  schedule:
    - cron: '0 2 * * *' # Daily at 2 AM UTC
  workflow_dispatch: # Manual trigger

jobs:
  sync-and-publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          always-auth: true
          registry-url: 'https://registry.npmjs.org'

      - uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Cache ip2region data
        uses: actions/cache@v4
        with:
          path: packages/ts-ip2region2-data/data/
          key: ip2region-data-${{ hashFiles('packages/ts-ip2region2-data/data/checksums.json') }}
          restore-keys: |
            ip2region-data-

      - name: Install dependencies
        run: |
          pnpm install --ignore-scripts
          find node_modules -name "7za" -type f -exec chmod +x {} \;

      - name: Build packages
        run: pnpm run build

      - name: Sync data
        id: sync
        run: |
          cd packages/ts-ip2region2-data
          if npm run sync-check; then
            echo "has_changes=true" >> $GITHUB_OUTPUT
          else
            echo "has_changes=false" >> $GITHUB_OUTPUT
          fi

      - name: Commit changes
        if: steps.sync.outputs.has_changes == 'true'
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          
          git add packages/ts-ip2region2-data/data/checksums.json
          git commit -m "feat(data): update ip2region database files"
          git push

      - name: Trigger release workflow
        if: steps.sync.outputs.has_changes == 'true'
        run: |
          curl -X POST \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            https://api.github.com/repos/${{ github.repository }}/dispatches \
            -d '{"event_type":"data_updated"}'
